[package]
name = "vcs"
version = "0.1.0"
edition = "2024"

[lib]
name = "vcs"
path = "src/lib.rs"

[dependencies]
iced = { version = "0.14", features = ["tokio", "image-without-codecs"] }
emumemory = { path = "../emumemory" }
emucpu = { path = "../emucpu" }

[profile.release]
debug = true
